/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package application.views;

import application.dao.SalesKMeansDao;
import application.daoimpl.SalesKMeansDaoImpl;
import application.models.SalesKMeansModel;
import application.utils.DataNormalizer;
import application.utils.MenuItem;
import java.util.ArrayList;
import java.util.List;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author mhdja
 */
public class DataAnalisaView extends javax.swing.JPanel {
    public final SalesKMeansDao salesKmeansDao;
    
    public void loadDataKMeans() {
        try {
            List<SalesKMeansModel> list = salesKmeansDao.findAll();

            DefaultTableModel model = new DefaultTableModel();
            model.setColumnIdentifiers(new Object[]{
                "Tahun", "Nama Menu", "Tipe Menu", "Total Terjual", "Omzet Per Menu"
            });

            for (SalesKMeansModel data : list) {
                model.addRow(new Object[]{
                    data.getTahun(),
                    data.getNamaMenu() + " - " + data.getTipeMenu(),
                    data.getTipeMenu(),
                    data.getTotalTerjualPerMenu(),
                    data.getOmzetPerMenu()
                });
            }

            jTable1.setModel(model);

        } catch (Exception e) {
            e.printStackTrace();
            JOptionPane.showMessageDialog(this, "Gagal memuat data analisa!");
        }
    }
    
    private void loadDataNormalisasiToTable() {
    try {
        // 1️⃣ Ambil data dari DB
        List<SalesKMeansModel> listFromDB = salesKmeansDao.findAll();

        // 2️⃣ Konversi ke MenuItem
        List<MenuItem> menuItems = new ArrayList<>();
        for (SalesKMeansModel sm : listFromDB) {

            double[] features = new double[]{
                sm.getTotalTerjualPerMenu(),
                sm.getOmzetPerMenu()
            };

            menuItems.add(new MenuItem(
                sm.getNamaMenu() + " - " + sm.getTipeMenu(),
                features
            ));
        }

        // 3️⃣ Normalisasi
        DataNormalizer.normalize(menuItems);

        // 4️⃣ Masukkan ke JTable2
        DefaultTableModel model = new DefaultTableModel();
        model.setColumnIdentifiers(new String[]{"Menu", "Total Terjual (Norm)", "Omzet (Norm)"});

        for (MenuItem mi : menuItems) {
            double[] f = mi.features;

            model.addRow(new Object[]{
                mi.nama,
                String.format("%.4f", f[0]),
                String.format("%.4f", f[1])
            });
        }

        jTable2.setModel(model);

    } catch (Exception e) {
        e.printStackTrace();
        JOptionPane.showMessageDialog(this, "Gagal load data normalisasi!", "Error", JOptionPane.ERROR_MESSAGE);
    }
}

    
    /**
     * Creates new form DataAnalisaView
     */
    public DataAnalisaView() {
        this.salesKmeansDao = new SalesKMeansDaoImpl();
         
        initComponents();
        
        loadDataKMeans();
        loadDataNormalisasiToTable();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jLabel2 = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTable2 = new javax.swing.JTable();
        jButton1 = new javax.swing.JButton();

        setBackground(new java.awt.Color(255, 255, 255));

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jLabel1.setText("Normalisasi Data");

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(jTable1);

        jLabel2.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jLabel2.setText("Data Analisa");

        jTable2.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane2.setViewportView(jTable2);

        jButton1.setText("Cetak Laporan");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 765, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addComponent(jScrollPane2)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jButton1)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel2)
                        .addGap(15, 15, 15))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(jButton1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)))
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 275, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 262, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTable jTable1;
    private javax.swing.JTable jTable2;
    // End of variables declaration//GEN-END:variables
}
