/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package application.views;

import application.dao.MenuMakananDao;
import application.dao.SalesDao;
import application.daoimpl.MenuMakananDaoImpl;
import application.daoimpl.SalesDaoImpl;
import application.models.MenuMakananModel;
import application.models.SalesModel;
import application.utils.ComboBoxItem;
import application.utils.ComboItem;
import application.utils.DatabaseUtil;
import java.io.InputStream;
import java.sql.Connection;
import java.util.ArrayList;
import java.util.HashMap;
import java.util.List;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import net.sf.jasperreports.engine.JRException;
import net.sf.jasperreports.engine.JasperCompileManager;
import net.sf.jasperreports.engine.JasperFillManager;
import net.sf.jasperreports.engine.JasperPrint;
import net.sf.jasperreports.engine.JasperReport;
import net.sf.jasperreports.engine.design.JasperDesign;
import net.sf.jasperreports.engine.xml.JRXmlLoader;
import net.sf.jasperreports.view.JasperViewer;

/**
 *
 * @author mhdja
 */
public class SalesView extends javax.swing.JPanel {
    public final SalesDao salesDao;
    public final MenuMakananDao menuMakananDao;
    private List<Integer> menuIdList = new ArrayList<>();

    
    public void getAllDataSales() {
        // Ambil data sales dari database
        List<SalesModel> salesList = salesDao.findAll();

        // Set Model untuk JTable
        DefaultTableModel model = new DefaultTableModel();
        model.setColumnIdentifiers(new Object[]{
            "ID Sales", "Menu (Tipe)", "Bulan - Tahun", "Total Terjual"
        });

        // Masukkan data sales ke dalam model JTable
        for (SalesModel sales : salesList) {
            model.addRow(new Object[]{
                sales.getIdSales(),
                sales.getNamaMenu() + " - " + sales.getTipeMenu(), // gabung nama + tipe
                sales.getBulanTahun(),
                sales.getTotalTerjual()
            });
        }

        // Set model ke JTable
        jTable1.setModel(model);
    }
 
    public void loadMenuToComboBox() {
        List<MenuMakananModel> menuList = menuMakananDao.findAll();
        jComboBox1.removeAllItems();
        menuIdList.clear(); // penting

        for (MenuMakananModel menu : menuList) {
            String label = menu.getNamaMenu() + " - " + menu.getTipeMenu();

            jComboBox1.addItem(label);

            // Simpan ID sesuai urutan item combobox
            menuIdList.add(menu.getIdMenu());
        }
    }
    
    public void loadBulanToComboBox() {
        String[] bulan = {
            "Januari", "Februari", "Maret", "April", "Mei", "Juni",
            "Juli", "Agustus", "September", "Oktober", "November", "Desember"
        };

        jComboBox2.removeAllItems();

        for (String b : bulan) {
            jComboBox2.addItem(b);
        }
    }
  
    /**
     * Creates new form SalesView
     */
    public SalesView() {
        this.salesDao = new SalesDaoImpl();
        this.menuMakananDao = new MenuMakananDaoImpl();
        
        initComponents();
        
        loadMenuToComboBox();
        loadBulanToComboBox();
        getAllDataSales();
        
        jTable1.getSelectionModel().addListSelectionListener(e -> {
            if (!e.getValueIsAdjusting() && jTable1.getSelectedRow() != -1) {
                int selectedRow = jTable1.getSelectedRow();

                // Ambil Total Terjual
                Object totalObj = jTable1.getValueAt(selectedRow, 3);
                String totalPenjualan = totalObj != null ? totalObj.toString() : "";
                jTextField2.setText(totalPenjualan);

                // Ambil Menu (Nama - Tipe) dan pilih di combobox
                String menuTipe = jTable1.getValueAt(selectedRow, 1).toString();
                jComboBox1.setSelectedItem(menuTipe);

                // Ambil Bulan dan Tahun dari "Bulan - Tahun"
                String bulanTahun = jTable1.getValueAt(selectedRow, 2).toString();
                String[] parts = bulanTahun.split(" "); // pisah "Bulan Tahun"

                if (parts.length >= 2) {
                    String bulan = parts[0];
                    String tahun = parts[1];

                    jComboBox2.setSelectedItem(bulan); // set bulan
                    jTextField1.setText(tahun);       // set tahun
                }
            }
        });


    }
    
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jComboBox1 = new javax.swing.JComboBox<>();
        jLabel3 = new javax.swing.JLabel();
        jComboBox2 = new javax.swing.JComboBox<>();
        jLabel4 = new javax.swing.JLabel();
        jTextField1 = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        jTextField2 = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jButton4 = new javax.swing.JButton();

        setBackground(new java.awt.Color(255, 255, 255));

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(jTable1);

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel1.setText("DATA PENJUALAN");

        jLabel2.setText("Nama Menu - Tipe Menu");

        jComboBox1.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        jLabel3.setText("Bulan");

        jComboBox2.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        jLabel4.setText("Tahun");

        jLabel5.setText("Total Penjualan");

        jButton1.setText("Simpan");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jButton2.setText("Ubah");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        jButton3.setText("Hapus");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });

        jButton4.setText("Cetak Laporan");
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 796, Short.MAX_VALUE))
            .addGroup(layout.createSequentialGroup()
                .addGap(14, 14, 14)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel4)
                            .addComponent(jLabel5))
                        .addGap(0, 700, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jButton1)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jButton2)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jButton3))
                            .addComponent(jLabel2)
                            .addComponent(jLabel1)
                            .addComponent(jLabel3)
                            .addComponent(jTextField2)
                            .addComponent(jTextField1)
                            .addComponent(jComboBox2, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jComboBox1, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jButton4)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addGap(18, 18, 18)
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jComboBox1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jLabel3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jComboBox2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel4)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jLabel5)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jTextField2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 9, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton1)
                    .addComponent(jButton2)
                    .addComponent(jButton3)
                    .addComponent(jButton4))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 270, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(27, 27, 27))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        // TODO add your handling code here:
        int selectedRow = jTable1.getSelectedRow();
        if (selectedRow == -1) {
            JOptionPane.showMessageDialog(this, "Pilih data yang akan dihapus!");
            return;
        }

        // Ambil ID Sales dari kolom 0 JTable
        int idSales = (int) jTable1.getValueAt(selectedRow, 0);

        // Konfirmasi sebelum delete
        int confirm = JOptionPane.showConfirmDialog(
                this, 
                "Apakah Anda yakin ingin menghapus data ini?", 
                "Konfirmasi Delete", 
                JOptionPane.YES_NO_OPTION
        );

        if (confirm == JOptionPane.YES_OPTION) {
            int result = salesDao.delete(idSales);
            if (result > 0) {
                JOptionPane.showMessageDialog(this, "Data berhasil dihapus!");
                getAllDataSales(); // refresh JTable
            } else {
                JOptionPane.showMessageDialog(this, "Delete gagal!");
            }
        }
    }//GEN-LAST:event_jButton3ActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
         try {
            // Ambil ID menu dari menuIdList
            int selectedIndex = jComboBox1.getSelectedIndex();
            if (selectedIndex == -1) {
                JOptionPane.showMessageDialog(this, "Silakan pilih menu.");
                return;
            }
            int idMenu = menuIdList.get(selectedIndex);

            // Ambil bulan (1–12)
            int bulan = jComboBox2.getSelectedIndex() + 1;

            // Ambil tahun
            int tahun = Integer.parseInt(jTextField1.getText());

            // Ambil total terjual
            int totalTerjual = Integer.parseInt(jTextField2.getText());

            // Buat model sales
            SalesModel sales = new SalesModel();
            sales.setIdMenu(idMenu);
            sales.setBulan(bulan);
            sales.setTahun(tahun);
            sales.setTotalTerjual(totalTerjual);

            // Simpan ke database
            int insertedId = salesDao.create(sales);

            JOptionPane.showMessageDialog(this, "Data berhasil disimpan! ID: " + insertedId);

            // Refresh tabel
            getAllDataSales();

        } catch (NumberFormatException nfe) {
            JOptionPane.showMessageDialog(this, "Tahun atau total terjual harus berupa angka.");
        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, "Gagal menyimpan data: " + e.getMessage());
        }
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
        // Ambil ID Sales dari JTable
        int selectedRow = jTable1.getSelectedRow();
        if (selectedRow == -1) {
            JOptionPane.showMessageDialog(this, "Pilih data yang akan diupdate!");
            return;
        }

        int idSales = (int) jTable1.getValueAt(selectedRow, 0); // kolom 0 = ID Sales

        // Ambil id_menu sesuai combobox (menuIdList sudah disiapkan)
        int menuIndex = jComboBox1.getSelectedIndex();
        if (menuIndex < 0) {
            JOptionPane.showMessageDialog(this, "Pilih menu!");
            return;
        }
        int idMenu = menuIdList.get(menuIndex);

        // Ambil bulan dan tahun dari combobox/textfield
        int bulan = jComboBox2.getSelectedIndex() + 1; // bulan 1-12
        int tahun;
        try {
            tahun = Integer.parseInt(jTextField1.getText());
        } catch (NumberFormatException ex) {
            JOptionPane.showMessageDialog(this, "Tahun tidak valid!");
            return;
        }

        // Ambil total terjual dari textfield
        int totalTerjual;
        try {
            totalTerjual = Integer.parseInt(jTextField2.getText());
        } catch (NumberFormatException ex) {
            JOptionPane.showMessageDialog(this, "Total Terjual tidak valid!");
            return;
        }

        // Buat objek SalesModel
        SalesModel sales = new SalesModel();
        sales.setIdSales(idSales);
        sales.setIdMenu(idMenu);
        sales.setBulan(bulan);
        sales.setTahun(tahun);
        sales.setTotalTerjual(totalTerjual);

        // Panggil update di DAO
        int result = salesDao.update(sales);
        if (result > 0) {
            JOptionPane.showMessageDialog(this, "Data berhasil diupdate!");
            getAllDataSales(); // refresh JTable
        } else {
            JOptionPane.showMessageDialog(this, "Update gagal!");
        }
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
        // TODO add your handling code here:
         try {
            String templateName = "LaporanPenjualan.jrxml";
            InputStream reportStream = ReportView.class.getResourceAsStream("/resources/reports/" + templateName);
            JasperDesign jd = JRXmlLoader.load(reportStream);

            Connection dbConnection = DatabaseUtil.getInstance().getConnection();

            JasperReport jr = JasperCompileManager.compileReport(jd);

            HashMap parameter = new HashMap();
            parameter.put("PATH","src/resources/images/");
            
            JasperPrint jp = JasperFillManager.fillReport(jr,parameter, dbConnection);
            JasperViewer.viewReport(jp, false);
        } catch (JRException ex) {
            Logger.getLogger(ReportView.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_jButton4ActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JComboBox<String> jComboBox1;
    private javax.swing.JComboBox<String> jComboBox2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JTextField jTextField2;
    // End of variables declaration//GEN-END:variables
}
