/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package application.views;

import application.dao.SalesKMeansDao;
import application.daoimpl.SalesKMeansDaoImpl;
import application.models.SalesKMeansModel;
import application.utils.DataNormalizer;
import application.utils.KmeansAlgoritma;
import application.utils.MenuItem;
import java.awt.BorderLayout;
import java.awt.Dimension;
import java.awt.Font;
import java.util.ArrayList;
import java.util.List;
import javax.swing.JScrollPane;
import javax.swing.JTextArea;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author mhdja
 */
public class SalesKmeansView extends javax.swing.JPanel {
    public final SalesKMeansDao salesKmeansDao;

    /**
     * Creates new form SalesKmeansView
     */
    public SalesKmeansView() {
        this.salesKmeansDao = new SalesKMeansDaoImpl();
        
        initComponents();
        
        loadKMeansData();
    }
    
    
     private void loadKMeansData() {
        try {
            // 1️⃣ Ambil data dari DAO
            List<SalesKMeansModel> listFromDB = salesKmeansDao.findAll();

            // 2️⃣ Konversi ke MenuItem (fitur KMeans)
            List<MenuItem> menuItems = new ArrayList<>();
            for (SalesKMeansModel sm : listFromDB) {

                // buat fitur
                double[] features = new double[]{
                    sm.getTotalTerjualPerMenu(),  // fitur 1
                    sm.getOmzetPerMenu()          // fitur 2
                };

                // log ke console
                System.out.println(
                    "[LOAD DATA] Menu: " + sm.getNamaMenu() +
                    " | Total Terjual: " + features[0] +
                    " | Omzet: " + features[1]
                );

                // buat objek MenuItem
                menuItems.add(new MenuItem(
                    sm.getNamaMenu() + " - " + sm.getTipeMenu(),
                    features
                ));

            }


            // 3️⃣ Normalisasi
            DataNormalizer.normalize(menuItems);

            // 4️⃣ Jalankan KMeans
            int k = 3; // jumlah cluster
            KmeansAlgoritma km = new KmeansAlgoritma(k, menuItems);
            km.run();
            
            // ⭐ 5️⃣ Sort hasil cluster ASC
            menuItems.sort((a, b) -> Integer.compare(a.cluster, b.cluster));
           

            // 5️⃣ Tampilkan hasil di JTable
            String[] columns = {"Nama Menu - Tipe", "Total Terjual", "Omzet", "Cluster", "Label"};
            DefaultTableModel model = new DefaultTableModel(columns, 0);

            for (MenuItem item : menuItems) {

                // tentukan label dari cluster (Java 11 compatible)
                String label;
                switch (item.cluster) {
                    case 0:
                        label = "Terlaris";
                        break;
                    case 1:
                        label = "Sedang";
                        break;
                    default:
                        label = "Kurang Laris";
                        break;
                }

                model.addRow(new Object[]{
                    item.nama,
                    item.features[0],
                    item.features[1],
                    item.cluster,
                    label
                });
            }


            jTable1.setModel(model);
            
            // Tampilkan hasil di JTextArea
            // Misal km.getSteps() mengembalikan List<String>
            List<String> steps = km.getSteps();

            // Gabungkan semua elemen menjadi satu string dengan newline (\n) sebagai pemisah
            String text = String.join("\n", steps);

            JTextArea txtHasil = new JTextArea();
            txtHasil.setEditable(false);
            txtHasil.setFont(new Font("Monospaced", Font.PLAIN, 12));
            txtHasil.setLineWrap(true);
            txtHasil.setWrapStyleWord(true);
            txtHasil.setText(text);
            
             JScrollPane scroll = new JScrollPane(txtHasil);
        scroll.setPreferredSize(new Dimension(jPanel1.getWidth(), jPanel1.getHeight()));

        jPanel1.removeAll();
        jPanel1.setLayout(new BorderLayout());
        jPanel1.add(scroll, BorderLayout.CENTER);
        jPanel1.revalidate();
        jPanel1.repaint();
        

        } catch (Exception e) {
            e.printStackTrace();
        }
    }
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jPanel1 = new javax.swing.JPanel();
        jButton1 = new javax.swing.JButton();

        setBackground(new java.awt.Color(255, 255, 255));

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(jTable1);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 371, Short.MAX_VALUE)
        );

        jButton1.setText("Cetak Laporan");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 828, Short.MAX_VALUE)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(jButton1)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 231, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(12, 12, 12)
                .addComponent(jButton1)
                .addContainerGap())
        );
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    // End of variables declaration//GEN-END:variables
}
